### ISSUE TITLE
Using multiple labels in helpers.nodePattern()

### ISSUE THREAD

**Issue by atonem** [Yomguithereal/decypher#29]
At this moment there seems to be no way to add multiple labels to a nodePattern since they are escaped. Maybe allow array and concatenate escaped labels?

**Comment by Yomguithereal** [comment]
Hello @atonem  I thought this was impossible to do with cypher? I thought only edges predicates could have multiple options. Let me check the syntax again and add a way to pass multiple labels by using an array if Cypher supports it.
