### ISSUE TITLE
allow `decypher` requiring from a relative path to other directories than the working directory

### ISSUE THREAD

**Issue by apopiak** [Yomguithereal/decypher#31]
## Example

with a project folder structure like so:

```
queries
    | read_graph.cypher
src
    | queries
        | read_graph.cypher
    | file.js
index.js
```
## Expected Behaviour:

I expect `decypher('./queries/read_graph.cypher')` to load either the one file (`./queries/read_graph.cypher` when calling `decypher()` in `index.js`) or the other (`./src/queries/read_graph.cypher` when calling `decypher()` in `file.js`).
## Actual Behaviour:

`decypher` always loads `./queries/read_graph.cypher` even when calling it from `file.js` because it uses `fs.readFileSync` [here](https://github.com/Yomguithereal/decypher/blob/master/src/loader.js#L100) which seems to work with the working directory instead of the directory where the file is present.

**Comment by apopiak** [comment]
can you have a look at this @Yomguithereal ?

**Comment by Yomguithereal** [comment]
Hello @apopiak. As a library function, decypher cannot know the path of the file containing the caller function using `decypher`. Usually, people use the `__dirname` node.js constant to perform what you want to do. Something like:

``` js
var path = require('path');

decypher(path.join(__dirname, 'queries', 'read_graph.cypher'));
```

**Comment by apopiak** [comment]
thx, decent workaround.
