### ISSUE TITLE
Missing 'Call' as a function option

### ISSUE THREAD

**Issue by dan-kez** [Yomguithereal/decypher#33]
at the moment you can't do something like 

```
var cypher = new Query();
cypher
   .match(...)
   .call('apoc.create.setLabels(...)');
```

See https://neo4j-contrib.github.io/neo4j-apoc-procedures/

**Comment by dan-kez** [comment]
As a note you can get around this by using .add('CALL apoc....') . But it would be nice to keep to the same paradigm

**Comment by Yomguithereal** [comment]
That's right indeed @dmk255. `CALL` was added very recently and I should therefore update the syntax.

**Comment by Yomguithereal** [comment]
Just added the `.call` method. Can you try & tell me whether this fits your needs before I release a new version on npm.
