### ISSUE TITLE
Ability to remove a 'return clause' or to add above it

### ISSUE THREAD

**Issue by dan-kez** [Yomguithereal/decypher#38]
I have made a few generic functions to do things like get some set of nodes (see pseudo code simple example below):

```
function getLabel
   cypher.match('(n:Label)')
      .return('n);

   return cypher;
```

I would like to reuse the base cypher query I wrote (in the above case `MATCH  (n:label)`) in other functions. e.g.:

```
function deleteNodesWithLabel
   var getLabelQuery = getLabel();
   var deleteQuery = new Query();

   deleteQuery.add(getLabelQuery)
        .delete('n');

   return deleteQuery;
```

The above is a pretty forced pseudo code example but being able to make modular cypher queries for reuse would be very powerful. 

I could, for the interim, just wait to put my `.return('n')` until I am actually about to run my query. However that forces all my functions to know about what my node variables are.

**Comment by dan-kez** [comment]
Follow up:

I think that this can be partially mitigated by allowing the use to pass in a `Query` object into `Query.prototype.segment`

I wrote up a PR for this: see #39

**Comment by Yomguithereal** [comment]
Since #39 has been merged, I guess we can close this. Be free to open it again if I got it wrong.
